spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/CoffeeFlavor/SpringcloudConfig.git
          default-label: master

server:
  port: 8888
